# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [17]:
import numpy as np
arr = np.random.randint(0,21, size=(4,7))
print(arr)

[[13 10 16 10 12 10 13]
 [ 6 17  2  0 19  6 15]
 [ 5  4  8 18  3  8  0]
 [11 17 20  5 15  5 11]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [18]:
arr = np.random.randint(0,11, size=(8,10))
sum = np.sum(arr, axis=1)
min_index = sum.argmin()
print(arr[min_index])

[4 3 0 5 1 3 5 7 1 5]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [19]:
import numpy as np
data = np.loadtxt(r"minutes_n_ingredients.csv", delimiter=",", dtype="int32", skiprows=1)
print(data[0:5, ])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [20]:
avg_value = np.mean(data[:,1], axis=0)
avg_value2 = np.mean(data[:,2], axis=0)
min_value = np.min(data[:,1], axis=0)
min_value2 = np.min(data[:,2], axis=0)
max_value = np.max(data[:,1], axis=0)
max_value2 = np.max(data[:,2], axis=0)
med_value = np.median(data[:,1], axis=0)
med_value2 = np.median(data[:,2], axis=0)

print(f"Среднее значение 2 столбца - {avg_value}")
print(f"Среднее значение 3 столбца - {avg_value2}")
print(f"Минимальное значение 2 столбца - {min_value}")
print(f"Минимальное значение 3 столбца - {min_value2}")
print(f"Максимальное значение 2 столбца - {max_value}")
print(f"Максимальное значение 3 столбца - {max_value2}")
print(f"Медианное значение 2 столбца - {med_value}")
print(f"Медианное значение 3 столбца - {med_value2}")

Среднее значение 2 столбца - 21601.00169
Среднее значение 3 столбца - 9.05528
Минимальное значение 2 столбца - 0
Минимальное значение 3 столбца - 1
Максимальное значение 2 столбца - 2147483647
Максимальное значение 3 столбца - 39
Медианное значение 2 столбца - 40.0
Медианное значение 3 столбца - 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [21]:
data_copy = data.copy()
print(len(data_copy[data_copy[:, 1] == 0]))
data_copy[data_copy[:, 1] == 0] = 1
print(len(data_copy[data_copy[:, 1] == 0]))

479
0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [22]:
print(len(np.unique(data[:, 1:])))

656


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [23]:
data_3, count = np.unique(data[:, 2], return_counts=True)
for i, j in zip(data_3, count):
    print(f"Кол-во ингридеентов-{i}, встретилось {j} раз")

Кол-во ингридеентов-1, встретилось 13 раз
Кол-во ингридеентов-2, встретилось 926 раз
Кол-во ингридеентов-3, встретилось 2895 раз
Кол-во ингридеентов-4, встретилось 5515 раз
Кол-во ингридеентов-5, встретилось 7913 раз
Кол-во ингридеентов-6, встретилось 9376 раз
Кол-во ингридеентов-7, встретилось 10628 раз
Кол-во ингридеентов-8, встретилось 10951 раз
Кол-во ингридеентов-9, встретилось 10585 раз
Кол-во ингридеентов-10, встретилось 9591 раз
Кол-во ингридеентов-11, встретилось 8297 раз
Кол-во ингридеентов-12, встретилось 6605 раз
Кол-во ингридеентов-13, встретилось 4997 раз
Кол-во ингридеентов-14, встретилось 3663 раз
Кол-во ингридеентов-15, встретилось 2595 раз
Кол-во ингридеентов-16, встретилось 1767 раз
Кол-во ингридеентов-17, встретилось 1246 раз
Кол-во ингридеентов-18, встретилось 790 раз
Кол-во ингридеентов-19, встретилось 573 раз
Кол-во ингридеентов-20, встретилось 376 раз
Кол-во ингридеентов-21, встретилось 217 раз
Кол-во ингридеентов-22, встретилось 161 раз
Кол-во ингридеентов-23, 

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [24]:
data_4 = data[data[:,2]<5]
print(data_4)

[[204134      5      3]
 [ 25623      6      4]
 [484223     18      4]
 ...
 [227056     30      4]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [25]:
data_5 = data.copy()
data_5 = [[data[:,1]/data[:,2]]]
print(max(data_5))

[array([ 3.75      ,  3.57142857,  1.66666667, ...,  4.33333333,
        1.25      , 10.        ])]


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [26]:
data_7 = data.copy()
sorted_data_7 = data_7[data_7[:, 1].argsort()[::-1]]
top_100_recipes = sorted_data_7[:100]
avg_ingr = np.average(top_100_recipes[:, 2])
print(avg_ingr)

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [27]:
rand_ind = np.random.choice(len(data[:,0]), size=10, replace=False)
rand_rec = data[rand_ind]
print(rand_rec)

[[436732     45     12]
 [272159     23      8]
 [165515    225      8]
 [397638    150     12]
 [317037     20     11]
 [322300     30     14]
 [ 47113     10      5]
 [309304      2      4]
 [ 68318     35     20]
 [144657     25     11]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [28]:
less_avg = data[data[:,2]<avg_value2]
p = len(less_avg)/len(data)
print(p*100,'%')

58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [29]:
good_recepts = np.zeros((data.shape[0], 4), dtype=int)
good_recepts[:, :3] = data
good_recepts[np.where((data[:, 2] <= 5) & (data[:, 1] <= 20)), 3] = 1
good_recepts

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [41]:
p = good_recepts[:,3].sum()/len(data)
print(p*100,'%')

9.552 %


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
short_recipes = data[data[:, 1] < 10]
standard_recipes = data[(data[:, 1] >= 10) & (data[:, 1] < 20)]
long_recipes = data[data[:, 1] >= 20]

max_length = min(len(short_recipes), len(standard_recipes), len(long_recipes))

three_dimensional_array = np.zeros((3, max_length, 3), dtype=int)

three_dimensional_array[0, :max_length, :] = short_recipes[:max_length]
three_dimensional_array[1, :max_length, :] = standard_recipes[:max_length]
three_dimensional_array[2, :max_length, :] = long_recipes[:max_length]

three_dimensional_array.shape, three_dimensional_array

((3, 7588, 3),
 array([[[ 67660,      5,      6],
         [366174,      7,      9],
         [204134,      5,      3],
         ...,
         [420725,      5,      3],
         [  4747,      0,      9],
         [370915,      5,      4]],
 
        [[ 94746,     10,      6],
         [ 33941,     18,      9],
         [446597,     15,      5],
         ...,
         [  9831,     15,      7],
         [335859,     12,     14],
         [256812,     10,      3]],
 
        [[127244,     60,     16],
         [ 23891,     25,      7],
         [157911,     60,     14],
         ...,
         [168901,     25,      7],
         [392339,     35,     13],
         [206732,     45,     10]]]))